### ISSUE TITLE
NPO-RT Implementation

### ISSUE THREAD

**Issue by chrisliu298** [licong-lin/negative-preference-optimization#1]
Thanks for releasing the code! As I read the code, I noticed that there are `npo`, `npo_grad_diff`, and `npo_KL`. I assume `npo` is the vanilla NPO described in the paper, and `npo_KL` is NPO-KL. I want to double-check if `npo_grad_diff` corresponds to the NPO-RT in the paper?

**Comment by licong-lin** [comment]
Yes! `npo_grad_diff` is the NPO-RT in the paper.
